services:
  app:
    build: .
    image: app
    container_name: stats_app
    ports:
      - "8080:8080"
    environment:
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - app.env
  db:
    image: mysql:latest
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD}
      start_period: 10s
      interval: 30s
      retries: 3
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=games_db
    volumes:
        - /var/lib/mysql